services:
  # API Service (Express)
  api:
    build: .
    container_name: phonebook-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=phonebook
    volumes:
      - .:/usr/src/app
    restart: always

  # Database Service (MySQL)
  db:
    image: mysql:8.0
    container_name: phonebook-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: phonebook
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

volumes:
  mysql_data:
    driver: local
